;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	electric-newline-and-maybe-indent
	indent-for-tab-command
	kill-region
	live-paredit-forward-kill-sexp
	paredit-backward-kill-word
	paredit-forward-delete
	paredit-forward-slurp-sexp
	paredit-newline
	paredit-open-round
	paredit-splice-sexp-killing-backward
	))

(setq mc/cmds-to-run-once
      '(
	))
